name: novaas
services:
  novaas:
    image: mongo:4.4.22
    restart: unless-stopped
    x-casaos:
      ports:
        - container: '1870'
          description:
            en_us: Mnovaas node-red Port
    ports:
      - target: 1870
        published: "1880"
        protocol: tcp
    container_name: novaas
x-casaos:
  architectures:
    - amd64
    - arm64
  main: novaas
  description:
    en_us: The NOVA Asset Administration Shell (NOVAAS) is an open source reference implementation and execution environment. The AAS implements the concept of the Digital Twin of a physical object turning it into an Industrie 4.0 component that facilitates interoperability in industrial applications.
 tagline:
    en_us: The NOVA Asset Administration Shell (NOVAAS) is an open source reference implementation and execution environment.
  screenshot_link: https://gitlab.com/novaas/catalog/nova-school-of-science-and-technology/novaas/-/raw/master/source/images/Screenshot_2020-12-15_at_22.20.37.png
  developer: NOVA School of Science and Technology
  author: novaas team
  icon: https://gitlab.com/novaas/catalog/nova-school-of-science-and-technology/novaas/-/raw/master/files/images/logo.png
  category: Developer
  title:
    en_us: NOVAAS
